#!/usr/bin/env python
# generated by create_forced_lc.py

from icecube.icetray import OMKey

doms_to_plot = []
dom_targets = []

doms_to_plot.append( {'name':"S09-D39",'T':-19.450003,'inice': "09-39",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(9,37))
dom_targets.append(OMKey(9,38))
dom_targets.append(OMKey(9,39))
dom_targets.append(OMKey(9,40))
dom_targets.append(OMKey(9,41))

doms_to_plot.append( {'name':"S41-D37",'T':-20.049994,'inice': "41-37",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(41,35))
dom_targets.append(OMKey(41,36))
dom_targets.append(OMKey(41,37))
dom_targets.append(OMKey(41,38))
dom_targets.append(OMKey(41,39))

doms_to_plot.append( {'name':"S44-D36",'T':-20.349997,'inice': "44-36",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(44,34))
dom_targets.append(OMKey(44,35))
dom_targets.append(OMKey(44,36))
dom_targets.append(OMKey(44,37))
dom_targets.append(OMKey(44,38))

doms_to_plot.append( {'name':"S42-D39",'T':-19.150000,'inice': "42-39",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(42,37))
dom_targets.append(OMKey(42,38))
dom_targets.append(OMKey(42,39))
dom_targets.append(OMKey(42,40))
dom_targets.append(OMKey(42,41))

doms_to_plot.append( {'name':"S18-D39",'T':-19.349997,'inice': "18-39",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(18,37))
dom_targets.append(OMKey(18,38))
dom_targets.append(OMKey(18,39))
dom_targets.append(OMKey(18,40))
dom_targets.append(OMKey(18,41))

doms_to_plot.append( {'name':"S69-D37",'T':-20.150000,'inice': "69-37",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(69,35))
dom_targets.append(OMKey(69,36))
dom_targets.append(OMKey(69,37))
dom_targets.append(OMKey(69,38))
dom_targets.append(OMKey(69,39))

doms_to_plot.append( {'name':"S47-D39",'T':-19.349997,'inice': "47-39",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(47,37))
dom_targets.append(OMKey(47,38))
dom_targets.append(OMKey(47,39))
dom_targets.append(OMKey(47,40))
dom_targets.append(OMKey(47,41))

doms_to_plot.append( {'name':"S67-D39",'T':-19.250006,'inice': "67-39",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(67,37))
dom_targets.append(OMKey(67,38))
dom_targets.append(OMKey(67,39))
dom_targets.append(OMKey(67,40))
dom_targets.append(OMKey(67,41))

doms_to_plot.append( {'name':"S17-D39",'T':-19.650000,'inice': "17-39",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(17,37))
dom_targets.append(OMKey(17,38))
dom_targets.append(OMKey(17,39))
dom_targets.append(OMKey(17,40))
dom_targets.append(OMKey(17,41))

doms_to_plot.append( {'name':"S20-D40",'T':-19.150000,'inice': "20-40",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(20,38))
dom_targets.append(OMKey(20,39))
dom_targets.append(OMKey(20,40))
dom_targets.append(OMKey(20,41))
dom_targets.append(OMKey(20,42))
