#!/usr/bin/env python
# generated by create_forced_lc.py

from icecube.icetray import OMKey

doms_to_plot = []
dom_targets = []

doms_to_plot.append( {'name':"S39-D57",'T':-10.650000,'inice': "39-57",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(39,55))
dom_targets.append(OMKey(39,56))
dom_targets.append(OMKey(39,57))
dom_targets.append(OMKey(39,58))
dom_targets.append(OMKey(39,59))

#doms_to_plot.append( {'name':"S32-D57",'T':-9.650000,'inice': "32-57",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(32,55))
dom_targets.append(OMKey(32,56))
dom_targets.append(OMKey(32,57))
dom_targets.append(OMKey(32,58))
dom_targets.append(OMKey(32,59))

doms_to_plot.append( {'name':"S02-D58",'T':-10.650000,'inice': "02-58",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(2,56))
dom_targets.append(OMKey(2,57))
dom_targets.append(OMKey(2,58))
dom_targets.append(OMKey(2,59))
dom_targets.append(OMKey(2,60))

doms_to_plot.append( {'name':"S31-D58",'T':-9.949988,'inice': "31-58",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(31,56))
dom_targets.append(OMKey(31,57))
dom_targets.append(OMKey(31,58))
dom_targets.append(OMKey(31,59))
dom_targets.append(OMKey(31,60))

doms_to_plot.append( {'name':"S22-D57",'T':-10.850012,'inice': "22-57",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(22,55))
dom_targets.append(OMKey(22,56))
dom_targets.append(OMKey(22,57))
dom_targets.append(OMKey(22,58))
dom_targets.append(OMKey(22,59))

doms_to_plot.append( {'name':"S73-D58",'T':-9.850012,'inice': "73-58",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(73,56))
dom_targets.append(OMKey(73,57))
dom_targets.append(OMKey(73,58))
dom_targets.append(OMKey(73,59))
dom_targets.append(OMKey(73,60))

doms_to_plot.append( {'name':"S62-D58",'T':-9.850012,'inice': "62-58",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(62,56))
dom_targets.append(OMKey(62,57))
dom_targets.append(OMKey(62,58))
dom_targets.append(OMKey(62,59))
dom_targets.append(OMKey(62,60))

doms_to_plot.append( {'name':"S64-D58",'T':-10.750006,'inice': "64-58",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(64,56))
dom_targets.append(OMKey(64,57))
dom_targets.append(OMKey(64,58))
dom_targets.append(OMKey(64,59))
dom_targets.append(OMKey(64,60))

doms_to_plot.append( {'name':"S56-D57",'T':-10.750006,'inice': "56-57",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(56,55))
dom_targets.append(OMKey(56,56))
dom_targets.append(OMKey(56,57))
dom_targets.append(OMKey(56,58))
dom_targets.append(OMKey(56,59))

doms_to_plot.append( {'name':"S01-D57",'T':-10.750006,'inice': "01-57",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(1,55))
dom_targets.append(OMKey(1,56))
dom_targets.append(OMKey(1,57))
dom_targets.append(OMKey(1,58))
dom_targets.append(OMKey(1,59))
