#!/usr/bin/env python
# generated by create_forced_lc.py

from icecube.icetray import OMKey

doms_to_plot = []
dom_targets = []

doms_to_plot.append( {'name':"S59-D08",'T':-30.349997,'inice': "59-08",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(59,6))
dom_targets.append(OMKey(59,7))
dom_targets.append(OMKey(59,8))
dom_targets.append(OMKey(59,9))
dom_targets.append(OMKey(59,10))

doms_to_plot.append( {'name':"S75-D07",'T':-29.650000,'inice': "75-07",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(75,5))
dom_targets.append(OMKey(75,6))
dom_targets.append(OMKey(75,7))
dom_targets.append(OMKey(75,8))
dom_targets.append(OMKey(75,9))

doms_to_plot.append( {'name':"S34-D05",'T':-30.150000,'inice': "34-05",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(34,3))
dom_targets.append(OMKey(34,4))
dom_targets.append(OMKey(34,5))
dom_targets.append(OMKey(34,6))
dom_targets.append(OMKey(34,7))

doms_to_plot.append( {'name':"S70-D06",'T':-29.750006,'inice': "70-06",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(70,4))
dom_targets.append(OMKey(70,5))
dom_targets.append(OMKey(70,6))
dom_targets.append(OMKey(70,7))
dom_targets.append(OMKey(70,8))

doms_to_plot.append( {'name':"S19-D04",'T':-30.349997,'inice': "19-04",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(19,2))
dom_targets.append(OMKey(19,3))
dom_targets.append(OMKey(19,4))
dom_targets.append(OMKey(19,5))
dom_targets.append(OMKey(19,6))

doms_to_plot.append( {'name':"S46-D07",'T':-29.650000,'inice': "46-07",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(46,5))
dom_targets.append(OMKey(46,6))
dom_targets.append(OMKey(46,7))
dom_targets.append(OMKey(46,8))
dom_targets.append(OMKey(46,9))

doms_to_plot.append( {'name':"S58-D05",'T':-30.250006,'inice': "58-05",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(58,3))
dom_targets.append(OMKey(58,4))
dom_targets.append(OMKey(58,5))
dom_targets.append(OMKey(58,6))
dom_targets.append(OMKey(58,7))

doms_to_plot.append( {'name':"S75-D06",'T':-29.750006,'inice': "75-06",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(75,4))
dom_targets.append(OMKey(75,5))
dom_targets.append(OMKey(75,6))
dom_targets.append(OMKey(75,7))
dom_targets.append(OMKey(75,8))

doms_to_plot.append( {'name':"S43-D03",'T':-30.349997,'inice': "43-03",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(43,1))
dom_targets.append(OMKey(43,2))
dom_targets.append(OMKey(43,3))
dom_targets.append(OMKey(43,4))
dom_targets.append(OMKey(43,5))

doms_to_plot.append( {'name':"S66-D05",'T':-29.950003,'inice': "66-05",'scale': 150,'spe': 75000,'qpair': 5})
dom_targets.append(OMKey(66,3))
dom_targets.append(OMKey(66,4))
dom_targets.append(OMKey(66,5))
dom_targets.append(OMKey(66,6))
dom_targets.append(OMKey(66,7))
